package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Berechtigung generated by hbm2java
 */
@Entity
@Table(name = "berechtigung", schema = "public"
)
public class Berechtigung implements java.io.Serializable {

    private BerechtigungId id;
    private Gruppe gruppe;
    private Lehrer lehrer;
    private boolean masterlehrer;

    public Berechtigung() {
    }

    public Berechtigung(Gruppe gruppe, Lehrer lehrer, boolean masterlehrer) {
        this.gruppe = gruppe;
        this.lehrer = lehrer;
        this.masterlehrer = masterlehrer;
    }
    
    public Berechtigung(BerechtigungId id, Gruppe gruppe, Lehrer lehrer, boolean masterlehrer) {
        this.id = id;
        this.gruppe = gruppe;
        this.lehrer = lehrer;
        this.masterlehrer = masterlehrer;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "lehrerKb", column = @Column(name = "lehrer_kb", nullable = false, length = 4)),
        @AttributeOverride(name = "grpId", column = @Column(name = "grp_id", nullable = false))})
    public BerechtigungId getId() {
        return this.id;
    }

    public void setId(BerechtigungId id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "grp_id", nullable = false, insertable = false, updatable = false)
    public Gruppe getGruppe() {
        return this.gruppe;
    }

    public void setGruppe(Gruppe gruppe) {
        this.gruppe = gruppe;
    }

    @ManyToOne
    @JoinColumn(name = "lehrer_kb", nullable = false, insertable = false, updatable = false)
    public Lehrer getLehrer() {
        return this.lehrer;
    }

    public void setLehrer(Lehrer lehrer) {
        this.lehrer = lehrer;
    }

    @Column(name = "masterlehrer", nullable = false)
    public boolean isMasterlehrer() {
        return this.masterlehrer;
    }

    public void setMasterlehrer(boolean masterlehrer) {
        this.masterlehrer = masterlehrer;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Berechtigung other = (Berechtigung) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(id);
    }

}
