package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bewertung generated by hbm2java
 */
@Entity
@Table(name = "bewertung", schema = "public"
)
public class Bewertung implements java.io.Serializable {

    private BewertungId id;
    private Kompetenzbereich kompetenzbereich;
    private LaufendeNote laufendeNote;
    private String maxbewertung;
    private String bewertung;
    private boolean setze5;

    public Bewertung() {
        id = new BewertungId();
    }
    
    public Bewertung(Kompetenzbereich kompetenzbereich, LaufendeNote laufendeNote, String maxbewertung, String bewertung, boolean setze5) {
        this.kompetenzbereich = kompetenzbereich;
        this.laufendeNote = laufendeNote;
        this.maxbewertung = maxbewertung;
        this.bewertung = bewertung;
        this.setze5 = setze5;
    }

    public Bewertung(BewertungId id, Kompetenzbereich kompetenzbereich, LaufendeNote laufendeNote, String maxbewertung, String bewertung, boolean setze5) {
        this.id = id;
        this.kompetenzbereich = kompetenzbereich;
        this.laufendeNote = laufendeNote;
        this.maxbewertung = maxbewertung;
        this.bewertung = bewertung;
        this.setze5 = setze5;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "laufId", column = @Column(name = "lauf_id", nullable = false)),
        @AttributeOverride(name = "kompId", column = @Column(name = "komp_id", nullable = false))})
    public BewertungId getId() {
        return this.id;
    }

    public void setId(BewertungId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "komp_id", nullable = false, insertable = false, updatable = false)
    public Kompetenzbereich getKompetenzbereich() {
        return this.kompetenzbereich;
    }

    public void setKompetenzbereich(Kompetenzbereich kompetenzbereich) {
        this.kompetenzbereich = kompetenzbereich;
        id.setKompId(kompetenzbereich.getKompId());
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "lauf_id", nullable = false, insertable = false, updatable = false)
    public LaufendeNote getLaufendeNote() {
        return this.laufendeNote;
    }

    public void setLaufendeNote(LaufendeNote laufendeNote) {
        this.laufendeNote = laufendeNote;
        id.setLaufId(laufendeNote.getLaufId());
    }

    @Column(name = "maxbewertung", nullable = false, length = 5)
    public String getMaxbewertung() {
        return this.maxbewertung;
    }

    public void setMaxbewertung(String maxbewertung) {
        this.maxbewertung = maxbewertung;
    }

    @Column(name = "bewertung", nullable = false, length = 5)
    public String getBewertung() {
        return this.bewertung;
    }

    public void setBewertung(String bewertung) {
        this.bewertung = bewertung;
    }

    @Column(name = "setze5", nullable = false)
    public boolean isSetze5() {
        return this.setze5;
    }

    public void setSetze5(boolean setze5) {
        this.setze5 = setze5;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.id);
        hash = 89 * hash + Objects.hashCode(this.kompetenzbereich);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bewertung other = (Bewertung) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.kompetenzbereich, other.kompetenzbereich)) {
            return false;
        }
        return true;
    }

    

}
