package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Direktionsdaten generated by hbm2java
 */
@Entity
@Table(name = "direktionsdaten", schema = "public"
)
public class Direktionsdaten implements java.io.Serializable {

    private String dirSchulkennzahl;
    private Lehrer lehrer;
    private Date dirKonfdatumsem1;
    private Date dirKonfdatumsem2;
    private Date dirSchulbeginn;
    private String dirSchulbez;
    private String dirSchuljahr;
    private String dirStr;
    private Date dirZeugnisdatumsem1;
    private Date dirZeugnisdatumsem2;

    public Direktionsdaten() {
    }

    public Direktionsdaten(String dirSchulkennzahl, Lehrer lehrer, Date dirKonfdatumsem1, Date dirKonfdatumsem2, Date dirSchulbeginn, String dirSchulbez, String dirSchuljahr, String dirStr, Date dirZeugnisdatumsem1, Date dirZeugnisdatumsem2) {
        this.dirSchulkennzahl = dirSchulkennzahl;
        this.lehrer = lehrer;
        this.dirKonfdatumsem1 = dirKonfdatumsem1;
        this.dirKonfdatumsem2 = dirKonfdatumsem2;
        this.dirSchulbeginn = dirSchulbeginn;
        this.dirSchulbez = dirSchulbez;
        this.dirSchuljahr = dirSchuljahr;
        this.dirStr = dirStr;
        this.dirZeugnisdatumsem1 = dirZeugnisdatumsem1;
        this.dirZeugnisdatumsem2 = dirZeugnisdatumsem2;
    }

    @Id
    @Column(name = "dir_schulkennzahl", unique = true, nullable = false, length = 6)
    public String getDirSchulkennzahl() {
        return this.dirSchulkennzahl;
    }

    public void setDirSchulkennzahl(String dirSchulkennzahl) {
        this.dirSchulkennzahl = dirSchulkennzahl;
    }

    @ManyToOne
    @JoinColumn(name = "dir_lehrer_kb", nullable = false)
    public Lehrer getLehrer() {
        return this.lehrer;
    }

    public void setLehrer(Lehrer lehrer) {
        this.lehrer = lehrer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dir_konfdatumsem1", nullable = false, length = 13)
    public Date getDirKonfdatumsem1() {
        return this.dirKonfdatumsem1;
    }

    public void setDirKonfdatumsem1(Date dirKonfdatumsem1) {
        this.dirKonfdatumsem1 = dirKonfdatumsem1;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dir_konfdatumsem2", nullable = false, length = 13)
    public Date getDirKonfdatumsem2() {
        return this.dirKonfdatumsem2;
    }

    public void setDirKonfdatumsem2(Date dirKonfdatumsem2) {
        this.dirKonfdatumsem2 = dirKonfdatumsem2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dir_schulbeginn", nullable = false, length = 13)
    public Date getDirSchulbeginn() {
        return this.dirSchulbeginn;
    }

    public void setDirSchulbeginn(Date dirSchulbeginn) {
        this.dirSchulbeginn = dirSchulbeginn;
    }

    @Column(name = "dir_schulbez", nullable = false, length = 150)
    public String getDirSchulbez() {
        return this.dirSchulbez;
    }

    public void setDirSchulbez(String dirSchulbez) {
        this.dirSchulbez = dirSchulbez;
    }

    @Column(name = "dir_schuljahr", nullable = false, length = 9)
    public String getDirSchuljahr() {
        return this.dirSchuljahr;
    }

    public void setDirSchuljahr(String dirSchuljahr) {
        this.dirSchuljahr = dirSchuljahr;
    }

    @Column(name = "dir_str", nullable = false, length = 35)
    public String getDirStr() {
        return this.dirStr;
    }

    public void setDirStr(String dirStr) {
        this.dirStr = dirStr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dir_zeugnisdatumsem1", nullable = false, length = 13)
    public Date getDirZeugnisdatumsem1() {
        return this.dirZeugnisdatumsem1;
    }

    public void setDirZeugnisdatumsem1(Date dirZeugnisdatumsem1) {
        this.dirZeugnisdatumsem1 = dirZeugnisdatumsem1;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dir_zeugnisdatumsem2", nullable = false, length = 13)
    public Date getDirZeugnisdatumsem2() {
        return this.dirZeugnisdatumsem2;
    }

    public void setDirZeugnisdatumsem2(Date dirZeugnisdatumsem2) {
        this.dirZeugnisdatumsem2 = dirZeugnisdatumsem2;
    }

}
