package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Erziehungsberechtigter generated by hbm2java
 */
@Entity
@Table(name = "erziehungsberechtigter", schema = "public"
)
@SequenceGenerator(name="erz_seq", sequenceName="erz_seq", allocationSize=1)
public class Erziehungsberechtigter implements java.io.Serializable {

    private int erzId;
    private Ort ort;
    private Schueler schueler;
    private Titel titel;
    private String erzVorname;
    private String erzZuname;
    private String erzStrasse;

    public Erziehungsberechtigter() {
    }

    public Erziehungsberechtigter(int erzId, Ort ort, Schueler schueler, String erzVorname, String erzZuname, String erzStrasse) {
        this.erzId = erzId;
        this.ort = ort;
        this.schueler = schueler;
        this.erzVorname = erzVorname;
        this.erzZuname = erzZuname;
        this.erzStrasse = erzStrasse;
    }

    public Erziehungsberechtigter(int erzId, Ort ort, Schueler schueler, Titel titel, String erzVorname, String erzZuname, String erzStrasse) {
        this.erzId = erzId;
        this.ort = ort;
        this.schueler = schueler;
        this.titel = titel;
        this.erzVorname = erzVorname;
        this.erzZuname = erzZuname;
        this.erzStrasse = erzStrasse;
    }

    @Id
    @GeneratedValue(generator = "erz_seq")
    @Column(name = "erz_id", unique = true, nullable = false)
    public int getErzId() {
        return this.erzId;
    }

    public void setErzId(int erzId) {
        this.erzId = erzId;
    }

    @ManyToOne
    @JoinColumn(name = "erz_ort_id", nullable = false)
    public Ort getOrt() {
        return this.ort;
    }

    public void setOrt(Ort ort) {
        this.ort = ort;
    }

    @ManyToOne
    @JoinColumn(name = "erz_ssd_id", nullable = false)
    public Schueler getSchueler() {
        return this.schueler;
    }

    public void setSchueler(Schueler schueler) {
        this.schueler = schueler;
    }

    @ManyToOne
    @JoinColumn(name = "erz_tit_id")
    public Titel getTitel() {
        return this.titel;
    }

    public void setTitel(Titel titel) {
        this.titel = titel;
    }

    @Column(name = "erz_vorname", nullable = false, length = 30)
    public String getErzVorname() {
        return this.erzVorname;
    }

    public void setErzVorname(String erzVorname) {
        this.erzVorname = erzVorname;
    }

    @Column(name = "erz_zuname", nullable = false, length = 30)
    public String getErzZuname() {
        return this.erzZuname;
    }

    public void setErzZuname(String erzZuname) {
        this.erzZuname = erzZuname;
    }

    @Column(name = "erz_strasse", nullable = false, length = 35)
    public String getErzStrasse() {
        return this.erzStrasse;
    }

    public void setErzStrasse(String erzStrasse) {
        this.erzStrasse = erzStrasse;
    }

}
