package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Gegenstand generated by hbm2java
 */
@Entity
@Table(name = "gegenstand", schema = "public")
public class Gegenstand implements java.io.Serializable, Comparable<Gegenstand> {

	private String gegKurzbez;
	private String gegLangbez;
	private String gegUpiskurzbez;
	private Set<LaufendeNote> laufendeNoten = new HashSet<>(0);
	private Set<Kompetenzbereich> kompetenzbereiche = new HashSet<>(0);
	private Set<Semesternote> semesternoten = new HashSet<>(0);
	private Set<Gruppe> gruppen = new HashSet<>(0);
	private Set<Kategorie> kategorien = new HashSet<>(0);
	private Set<Mahnung> mahnungen = new HashSet<>(0);
	private Set<Lehrfach> lehrfaecher = new HashSet<>(0);

	public Gegenstand() {
	}

	public Gegenstand(String gegKurzbez, String gegLangbez, String gegUpiskurzbez) {
		this.gegKurzbez = gegKurzbez;
		this.gegLangbez = gegLangbez;
		this.gegUpiskurzbez = gegUpiskurzbez;
	}

	public Gegenstand(String gegKurzbez, String gegLangbez, String gegUpiskurzbez, Set<LaufendeNote> laufendeNotes, Set<Kompetenzbereich> kompetenzbereiche, Set<Semesternote> semesternotes, Set<Gruppe> gruppes, Set<Kategorie> kategories, Set<Mahnung> mahnungs, Set<Lehrfach> lehrfaches) {
		this.kompetenzbereiche = kompetenzbereiche;
		this.gegKurzbez = gegKurzbez;
		this.gegLangbez = gegLangbez;
		this.gegUpiskurzbez = gegUpiskurzbez;
		this.laufendeNoten = laufendeNotes;
		this.semesternoten = semesternotes;
		this.gruppen = gruppes;
		this.kategorien = kategories;
		this.mahnungen = mahnungs;
		this.lehrfaecher = lehrfaches;
	}

	@Id
	@Column(name = "geg_kurzbez", unique = true, nullable = false, length = 6)
	public String getGegKurzbez() {
		return this.gegKurzbez;
	}

	public void setGegKurzbez(String gegKurzbez) {
		this.gegKurzbez = gegKurzbez;
	}

	@Column(name = "geg_langbez", nullable = false, length = 100)
	public String getGegLangbez() {
		return this.gegLangbez;
	}

	public void setGegLangbez(String gegLangbez) {
		this.gegLangbez = gegLangbez;
	}

	@Column(name = "geg_upiskurzbez", nullable = false, length = 4)
	public String getGegUpiskurzbez() {
		return this.gegUpiskurzbez;
	}

	public void setGegUpiskurzbez(String gegUpiskurzbez) {
		this.gegUpiskurzbez = gegUpiskurzbez;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<LaufendeNote> getLaufendeNoten() {
		return this.laufendeNoten;
	}

	public void setLaufendeNoten(Set<LaufendeNote> laufendeNoten) {
		this.laufendeNoten = laufendeNoten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<Kompetenzbereich> getKompetenzbereiche() {
		return this.kompetenzbereiche;
	}

	public void setKompetenzbereiche(Set<Kompetenzbereich> kompetenzbereiche) {
		this.kompetenzbereiche = kompetenzbereiche;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<Semesternote> getSemesternoten() {
		return this.semesternoten;
	}

	public void setSemesternoten(Set<Semesternote> semesternoten) {
		this.semesternoten = semesternoten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<Gruppe> getGruppen() {
		return this.gruppen;
	}

	public void setGruppen(Set<Gruppe> gruppen) {
		this.gruppen = gruppen;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "gegenstaende")
	public Set<Kategorie> getKategorien() {
		return this.kategorien;
	}

	public void setKategorien(Set<Kategorie> kategorien) {
		this.kategorien = kategorien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<Mahnung> getMahnungen() {
		return this.mahnungen;
	}

	public void setMahnungen(Set<Mahnung> mahnungen) {
		this.mahnungen = mahnungen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gegenstand")
	public Set<Lehrfach> getLehrfaecher() {
		return this.lehrfaecher;
	}

	public void setLehrfaecher(Set<Lehrfach> lehrfaecher) {
		this.lehrfaecher = lehrfaecher;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 89 * hash + Objects.hashCode(this.gegKurzbez);
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Gegenstand other = (Gegenstand) obj;
		return Objects.equals(this.gegKurzbez, other.gegKurzbez);
	}

	@Override
	public String toString() {
		return gegKurzbez;
	}

	@Override
	public int compareTo(Gegenstand g) {
		return gegKurzbez.compareTo(g.gegKurzbez);
	}

	@Transient
	public List<LaufendeNote> getLaufendeNotenList() {
		return new ArrayList<>(getLaufendeNoten());
	}
}
