package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Kategorie generated by hbm2java
 */
@Entity
@Table(name = "kategorie", schema = "public"
)
@SequenceGenerator(name="kat_seq", sequenceName="kat_seq", allocationSize=1)
public class Kategorie implements java.io.Serializable {

    private int katId;                    //Primärschlüssel in der Datenbank
    private Gesetzkategorie gesetzkategorie;    //Gesetzeskategorie 
    private Lehrer lehrer;          //Lehrer, welcher die Kategorie erstellt hat
    private boolean katAnzeigeNoten;    //true: Noten werden angezeigt, false: Zeichen(+,~+,~,~-,-)
    private String katBezeichnung;      //Bezeichnung der Kategorie
    private String katEingabeart;       //Noteneingabeart: Noten(1-5),Abgestufte Noten(+1,1,-1,..), Punkte
    private int katGewichtArbeit;       //Gewichtung einer Arbeit
    private int katMax;                 //Maximal erreichbare Punkte
    private Integer katMaxgewichtung;   //Maximalgewichtung der gesamten Kategorie
    private boolean katOeffentlichflag; //true: Kategorie kann von anderen Lehrkräften verwendet werden
    private double katPw1;      //Grenze für Sehr Gut
    private double katPw2;      //Grenze für Gut
    private double katPw3;      //Grenze für Befriedigend
    private double katPw4;      //Grenze für Sehr Gut
    private Set<Gegenstand> gegenstaende = new HashSet<Gegenstand>(0);
    private Set<LaufendeNote> laufendeNoten = new HashSet<LaufendeNote>(0);

    public Kategorie() {
    }

    public Kategorie(Gesetzkategorie gesetzkategorie, Lehrer lehrer, boolean katAnzeigeNoten, String katBezeichnung, String katEingabeart, int katGewichtArbeit, int katMax, boolean katOeffentlichflag, double katPw1, double katPw2, double katPw3, double katPw4) {
        this.katId = katId;
        this.gesetzkategorie = gesetzkategorie;
        this.lehrer = lehrer;
        this.katAnzeigeNoten = katAnzeigeNoten;
        this.katBezeichnung = katBezeichnung;
        this.katEingabeart = katEingabeart;
        this.katGewichtArbeit = katGewichtArbeit;
        this.katMax = katMax;
        this.katOeffentlichflag = katOeffentlichflag;
        this.katPw1 = katPw1;
        this.katPw2 = katPw2;
        this.katPw3 = katPw3;
        this.katPw4 = katPw4;
    }

    public Kategorie(int katId, Gesetzkategorie gesetzkategorie, Lehrer lehrer, boolean katAnzeigeNoten, String katBezeichnung, String katEingabeart, int katGewichtArbeit, int katMax, boolean katOeffentlichflag, double katPw1, double katPw2, double katPw3, double katPw4) {
        this.katId = katId;
        this.gesetzkategorie = gesetzkategorie;
        this.lehrer = lehrer;
        this.katAnzeigeNoten = katAnzeigeNoten;
        this.katBezeichnung = katBezeichnung;
        this.katEingabeart = katEingabeart;
        this.katGewichtArbeit = katGewichtArbeit;
        this.katMax = katMax;
        this.katOeffentlichflag = katOeffentlichflag;
        this.katPw1 = katPw1;
        this.katPw2 = katPw2;
        this.katPw3 = katPw3;
        this.katPw4 = katPw4;
    }

    public Kategorie(int katId, Gesetzkategorie gesetzkategorie, Lehrer lehrer, boolean katAnzeigeNoten, String katBezeichnung, String katEingabeart, int katGewichtArbeit, int katMax, Integer katMaxgewichtung, boolean katOeffentlichflag, double katPw1, double katPw2, double katPw3, double katPw4, Set<Gegenstand> gegenstands, Set<LaufendeNote> laufendeNotes) {
        this.katId = katId;
        this.gesetzkategorie = gesetzkategorie;
        this.lehrer = lehrer;
        this.katAnzeigeNoten = katAnzeigeNoten;
        this.katBezeichnung = katBezeichnung;
        this.katEingabeart = katEingabeart;
        this.katGewichtArbeit = katGewichtArbeit;
        this.katMax = katMax;
        this.katMaxgewichtung = katMaxgewichtung;
        this.katOeffentlichflag = katOeffentlichflag;
        this.katPw1 = katPw1;
        this.katPw2 = katPw2;
        this.katPw3 = katPw3;
        this.katPw4 = katPw4;
        this.gegenstaende = gegenstands;
        this.laufendeNoten = laufendeNotes;
    }
    
    public Kategorie(Kategorie kategorie) {
        this(0, kategorie.gesetzkategorie, kategorie.lehrer, 
                kategorie.katAnzeigeNoten, kategorie.katBezeichnung, 
                kategorie.katEingabeart, kategorie.katGewichtArbeit, 
                kategorie.katMax, kategorie.katMaxgewichtung,
                kategorie.katOeffentlichflag, 
                kategorie.katPw1, kategorie.katPw2, 
                kategorie.katPw3, kategorie.katPw4,
                kategorie.gegenstaende, kategorie.laufendeNoten);
    }

    @Id
    @GeneratedValue(generator = "kat_seq")
    @Column(name = "kat_id", unique = true, nullable = false)
    public int getKatId() {
        return this.katId;
    }

    public void setKatId(int katId) {
        this.katId = katId;
    }

    @ManyToOne
    @JoinColumn(name = "kat_ges_kurzbez", nullable = false)
    public Gesetzkategorie getGesetzkategorie() {
        return this.gesetzkategorie;
    }

    public void setGesetzkategorie(Gesetzkategorie gesetzkategorie) {
        this.gesetzkategorie = gesetzkategorie;
    }

    @ManyToOne
    @JoinColumn(name = "kat_lehrer_kb", nullable = false)
    public Lehrer getLehrer() {
        return this.lehrer;
    }

    public void setLehrer(Lehrer lehrer) {
        this.lehrer = lehrer;
    }

    @Column(name = "kat_anzeige_noten", nullable = false)
    public boolean isKatAnzeigeNoten() {
        return this.katAnzeigeNoten;
    }

    public void setKatAnzeigeNoten(boolean katAnzeigeNoten) {
        this.katAnzeigeNoten = katAnzeigeNoten;
    }

    @Column(name = "kat_bezeichnung", nullable = false, length = 40)
    public String getKatBezeichnung() {
        return this.katBezeichnung;
    }

    public void setKatBezeichnung(String katBezeichnung) {
        this.katBezeichnung = katBezeichnung;
    }

    @Column(name = "kat_eingabeart", nullable = false, length = 1)
    public String getKatEingabeart() {
        return this.katEingabeart;
    }

    public void setKatEingabeart(String katEingabeart) {
        this.katEingabeart = katEingabeart;
    }

    @Column(name = "kat_gewicht_arbeit", nullable = false)
    public int getKatGewichtArbeit() {
        return this.katGewichtArbeit;
    }

    public void setKatGewichtArbeit(int katGewichtArbeit) {
        this.katGewichtArbeit = katGewichtArbeit;
    }

    @Column(name = "kat_max", nullable = false)
    public int getKatMax() {
        return this.katMax;
    }

    public void setKatMax(int katMax) {
        this.katMax = katMax;
    }

    @Column(name = "kat_maxgewichtung")
    public Integer getKatMaxgewichtung() {
        return this.katMaxgewichtung;
    }

    public void setKatMaxgewichtung(Integer katMaxgewichtung) {
        this.katMaxgewichtung = katMaxgewichtung;
    }

    @Column(name = "kat_oeffentlichflag", nullable = false)
    public boolean isKatOeffentlichflag() {
        return this.katOeffentlichflag;
    }

    public void setKatOeffentlichflag(boolean katOeffentlichflag) {
        this.katOeffentlichflag = katOeffentlichflag;
    }

    @Column(name = "kat_pw1", nullable = false)
    public double getKatPw1() {
        return this.katPw1;
    }

    public void setKatPw1(double katPw1) {
        this.katPw1 = katPw1;
    }

    @Column(name = "kat_pw2", nullable = false)
    public double getKatPw2() {
        return this.katPw2;
    }

    public void setKatPw2(double katPw2) {
        this.katPw2 = katPw2;
    }

    @Column(name = "kat_pw3", nullable = false)
    public double getKatPw3() {
        return this.katPw3;
    }

    public void setKatPw3(double katPw3) {
        this.katPw3 = katPw3;
    }

    @Column(name = "kat_pw4", nullable = false)
    public double getKatPw4() {
        return this.katPw4;
    }

    public void setKatPw4(double katPw4) {
        this.katPw4 = katPw4;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "kat_zu_geg", schema = "public", joinColumns = {
        @JoinColumn(name = "kat_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "geg_kurzbez", nullable = false, updatable = false)})
    public Set<Gegenstand> getGegenstaende() {
        return this.gegenstaende;
    }

    public void setGegenstaende(Set<Gegenstand> gegenstaende) {
        this.gegenstaende = gegenstaende;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "kategorie")
    public Set<LaufendeNote> getLaufendeNoten() {
        return this.laufendeNoten;
    }

    public void setLaufendeNoten(Set<LaufendeNote> laufendeNoten) {
        this.laufendeNoten = laufendeNoten;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + this.katId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Kategorie other = (Kategorie) obj;
        if (this.katId != other.katId) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return katBezeichnung;
    }

}
