package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Klasse generated by hbm2java
 */
@Entity
@Table(name = "klasse", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "kla_lehrer_kb"))
public class Klasse implements java.io.Serializable, Comparable<Klasse> {

	private String klaBez;
	private Lehrer lehrer;
	private Set<Lehrfach> lehrfaecher = new HashSet<>(0);
	private Set<Schueler> schueler = new HashSet<>(0);

	public Klasse() {
	}

	public Klasse(String klaBez) {
		this.schueler = new HashSet<>(0);
		this.klaBez = klaBez;
	}

	public Klasse(String klaBez, Lehrer lehrer, Set<Lehrfach> lehrfaches, Set<Schueler> schuelers) {
		this.schueler = new HashSet<>(0);
		this.klaBez = klaBez;
		this.lehrer = lehrer;
		this.lehrfaecher = lehrfaches;
		this.schueler = schuelers;
	}

	@Id
	@Column(name = "kla_bez", unique = true, nullable = false, length = 8)
	public String getKlaBez() {
		return this.klaBez;
	}

	public void setKlaBez(String klaBez) {
		this.klaBez = klaBez;
	}

	@ManyToOne
	@JoinColumn(name = "kla_lehrer_kb", unique = true)
	public Lehrer getLehrer() {
		return this.lehrer;
	}

	public void setLehrer(Lehrer lehrer) {
		this.lehrer = lehrer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klasse")
	public Set<Lehrfach> getLehrfaecher() {
		return this.lehrfaecher;
	}

	public void setLehrfaecher(Set<Lehrfach> lehrfaecher) {
		this.lehrfaecher = lehrfaecher;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klasse")
	public Set<Schueler> getSchueler() {
		return this.schueler;
	}

	public void setSchueler(Set<Schueler> schueler) {
		this.schueler = schueler;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 71 * hash + Objects.hashCode(this.klaBez);
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Klasse other = (Klasse) obj;
		return Objects.equals(this.klaBez, other.klaBez);
	}

	@Override
	public int compareTo(Klasse k) {
		return this.klaBez.compareTo(k.klaBez);
	}

        
        //Geändert am 15.11.2017(Alexandru Bejinariu, 5AHIF)
    @Override
    public String toString() {
        return this.klaBez; 
    }
        
        
}
