package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Kompetenzbereich generated by hbm2java
 */
@Entity
@Table(name = "kompetenzbereich", schema = "public"
)
@SequenceGenerator(name="komp_seq", sequenceName="komp_seq", allocationSize=1)
public class Kompetenzbereich implements java.io.Serializable {

    private int kompId;
    private Gegenstand gegenstand;
    private String kompBezeichnung;
    private String kompLehrinhalt;
    private int kompSemester;
    private int kompJahrgang;
    private Set<Bewertung> bewertungen = new HashSet<Bewertung>(0);
    private Set<Pruefung> pruefungen = new HashSet<Pruefung>(0);

    public Kompetenzbereich() {
    }

    public Kompetenzbereich(Gegenstand gegenstand, String kompBezeichnung, String kompLehrinhalt, int kompSemester, int kompJahrgang) {
        this.gegenstand = gegenstand;
        this.kompBezeichnung = kompBezeichnung;
        this.kompLehrinhalt = kompLehrinhalt;
        this.kompSemester = kompSemester;
        this.kompJahrgang = kompJahrgang;
    }

    public Kompetenzbereich(int kompId, Gegenstand gegenstand, String kompBezeichnung, String kompLehrinhalt, int kompSemester, int kompJahrgang) {
        this.kompId = kompId;
        this.gegenstand = gegenstand;
        this.kompBezeichnung = kompBezeichnung;
        this.kompLehrinhalt = kompLehrinhalt;
        this.kompSemester = kompSemester;
        this.kompJahrgang = kompJahrgang;
    }

    public Kompetenzbereich(int kompId, Gegenstand gegenstand, String kompBezeichnung, String kompLehrinhalt, int kompSemester, int kompJahrgang, Set<Bewertung> bewertungs, Set<Pruefung> pruefungs) {
        this.kompId = kompId;
        this.gegenstand = gegenstand;
        this.kompBezeichnung = kompBezeichnung;
        this.kompLehrinhalt = kompLehrinhalt;
        this.kompSemester = kompSemester;
        this.kompJahrgang = kompJahrgang;
        this.bewertungen = bewertungs;
        this.pruefungen = pruefungs;
    }

    @Id
    @GeneratedValue(generator = "komp_seq")
    @Column(name = "komp_id", unique = true, nullable = false)
    public int getKompId() {
        return this.kompId;
    }

    public void setKompId(int kompId) {
        this.kompId = kompId;
    }

    @ManyToOne
    @JoinColumn(name = "komp_geg_kurzbez", nullable = false)
    public Gegenstand getGegenstand() {
        return this.gegenstand;
    }

    public void setGegenstand(Gegenstand gegenstand) {
        this.gegenstand = gegenstand;
    }

    @Column(name = "komp_bezeichnung", nullable = false)
    public String getKompBezeichnung() {
        return this.kompBezeichnung;
    }

    public void setKompBezeichnung(String kompBezeichnung) {
        this.kompBezeichnung = kompBezeichnung;
    }

    @Column(name = "komp_lehrinhalt", nullable = false)
    public String getKompLehrinhalt() {
        return this.kompLehrinhalt;
    }

    public void setKompLehrinhalt(String kompLehrinhalt) {
        this.kompLehrinhalt = kompLehrinhalt;
    }

    @Column(name = "komp_semester", nullable = false)
    public int getKompSemester() {
        return this.kompSemester;
    }

    public void setKompSemester(int kompSemester) {
        this.kompSemester = kompSemester;
    }

    @Column(name = "komp_jahrgang", nullable = false)
    public int getKompJahrgang() {
        return this.kompJahrgang;
    }

    public void setKompJahrgang(int kompJahrgang) {
        this.kompJahrgang = kompJahrgang;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "kompetenzbereich",
            cascade = CascadeType.PERSIST)
    public Set<Bewertung> getBewertungen() {
        return this.bewertungen;
    }

    public void setBewertungen(Set<Bewertung> bewertungen) {
        this.bewertungen = bewertungen;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "kompetenzbereiche")
    public Set<Pruefung> getPruefungen() {
        return this.pruefungen;
    }

    public void setPruefungen(Set<Pruefung> pruefungen) {
        this.pruefungen = pruefungen;
    }

    @Override
    public String toString() {
        return kompBezeichnung;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + this.kompId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Kompetenzbereich other = (Kompetenzbereich) obj;
        if (this.kompId != other.kompId) {
            return false;
        }
        return true;
    }
}
