package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LehrfachId generated by hbm2java
 */
@Embeddable
public class LehrfachId implements java.io.Serializable {

    private String klaBez;
    private String gegKurzbez;
    private String lehrerKb;

    public LehrfachId() {
    }

    public LehrfachId(String klaBez, String gegKurzbez, String lehrerKb) {
        this.klaBez = klaBez;
        this.gegKurzbez = gegKurzbez;
        this.lehrerKb = lehrerKb;
    }

    @Column(name = "kla_bez", nullable = false, length = 8)
    public String getKlaBez() {
        return this.klaBez;
    }

    public void setKlaBez(String klaBez) {
        this.klaBez = klaBez;
    }

    @Column(name = "geg_kurzbez", nullable = false, length = 6)
    public String getGegKurzbez() {
        return this.gegKurzbez;
    }

    public void setGegKurzbez(String gegKurzbez) {
        this.gegKurzbez = gegKurzbez;
    }

    @Column(name = "lehrer_kb", nullable = false, length = 4)
    public String getLehrerKb() {
        return this.lehrerKb;
    }

    public void setLehrerKb(String lehrerKb) {
        this.lehrerKb = lehrerKb;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof LehrfachId)) {
            return false;
        }
        LehrfachId castOther = (LehrfachId) other;

        return ((this.getKlaBez() == castOther.getKlaBez()) || (this.getKlaBez() != null && castOther.getKlaBez() != null && this.getKlaBez().equals(castOther.getKlaBez())))
                && ((this.getGegKurzbez() == castOther.getGegKurzbez()) || (this.getGegKurzbez() != null && castOther.getGegKurzbez() != null && this.getGegKurzbez().equals(castOther.getGegKurzbez())))
                && ((this.getLehrerKb() == castOther.getLehrerKb()) || (this.getLehrerKb() != null && castOther.getLehrerKb() != null && this.getLehrerKb().equals(castOther.getLehrerKb())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKlaBez() == null ? 0 : this.getKlaBez().hashCode());
        result = 37 * result + (getGegKurzbez() == null ? 0 : this.getGegKurzbez().hashCode());
        result = 37 * result + (getLehrerKb() == null ? 0 : this.getLehrerKb().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "LehrfachId{" + "klaBez=" + klaBez + ", gegKurzbez=" + gegKurzbez + ", lehrerKb=" + lehrerKb + '}';
    }
}
