package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lehrfach generated by hbm2java
 */
@Entity
@Table(name = "lehrfach", schema = "public"
)
public class Lehrfach implements java.io.Serializable {

    private LehrfachId id;
    private Gegenstand gegenstand;
    private Klasse klasse;
    private Lehrer lehrer;

    public Lehrfach() {
    }

    public Lehrfach(Gegenstand gegenstand, Klasse klasse, Lehrer lehrer) {
        this.gegenstand = gegenstand;
        this.klasse = klasse;
        this.lehrer = lehrer;
    }
    
    public Lehrfach(LehrfachId id, Gegenstand gegenstand, Klasse klasse, Lehrer lehrer) {
        this.id = id;
        this.gegenstand = gegenstand;
        this.klasse = klasse;
        this.lehrer = lehrer;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "klaBez", column = @Column(name = "kla_bez", nullable = false, length = 8)),
        @AttributeOverride(name = "gegKurzbez", column = @Column(name = "geg_kurzbez", nullable = false, length = 6)),
        @AttributeOverride(name = "lehrerKb", column = @Column(name = "lehrer_kb", nullable = false, length = 4))})
    public LehrfachId getId() {
        return this.id;
    }

    public void setId(LehrfachId id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "geg_kurzbez", nullable = false, insertable = false, updatable = false)
    public Gegenstand getGegenstand() {
        return this.gegenstand;
    }

    public void setGegenstand(Gegenstand gegenstand) {
        this.gegenstand = gegenstand;
    }

    @ManyToOne
    @JoinColumn(name = "kla_bez", nullable = false, insertable = false, updatable = false)
    public Klasse getKlasse() {
        return this.klasse;
    }

    public void setKlasse(Klasse klasse) {
        this.klasse = klasse;
    }

    @ManyToOne
    @JoinColumn(name = "lehrer_kb", nullable = false, insertable = false, updatable = false)
    public Lehrer getLehrer() {
        return this.lehrer;
    }

    public void setLehrer(Lehrer lehrer) {
        this.lehrer = lehrer;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Lehrfach other = (Lehrfach) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}
