package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lehrer generated by hbm2java
 */
@Entity
@Table(name = "lehrer", schema = "public")
public class Lehrer implements java.io.Serializable {

    private String lehrerKb;
    private Titel titel;
    private String lehrerVorname;
    private String lehrerZuname;
    private String lehrerPasswort;
    private String lehrerSvnr;
    private String lehrerEmail;
    private Double lehrerMaxnegativ;
    private String lehrerTelefonnr;
    private boolean lehrerIstAv;
    private boolean lehrerIstTelVer;
    private String lehrerGeschlecht;
    private Set<LaufendeNote> laufendeNoten = new HashSet<LaufendeNote>(0);
    private Set<Semesternote> semesternoten = new HashSet<Semesternote>(0);
    private Set<Sprechstunde> sprechstunden = new HashSet<Sprechstunde>(0);
    private Set<Berechtigung> berechtigungen = new HashSet<Berechtigung>(0);
    private Set<Klasse> klassen = new HashSet<Klasse>(0);
    private Set<Kategorie> kategorien = new HashSet<Kategorie>(0);
    private Set<Direktionsdaten> direktionsdaten = new HashSet<Direktionsdaten>(0);
    private Set<Lehrfach> lehrfaecher = new HashSet<Lehrfach>(0);
    private Set<Pruefung> pruefungen = new HashSet<Pruefung>(0);
    private Set<Mahnung> mahnungen = new HashSet<Mahnung>(0);

    public Lehrer() {
    }

    public Lehrer(String lehrerKb, String lehrerVorname, String lehrerZuname, String lehrerPasswort, String lehrerSvnr, String lehrerEmail, boolean lehrerIstAv, boolean lehrerIstTelVer, String lehrerGeschlecht) {
        this.lehrerKb = lehrerKb;
        this.lehrerVorname = lehrerVorname;
        this.lehrerZuname = lehrerZuname;
        this.lehrerPasswort = lehrerPasswort;
        this.lehrerSvnr = lehrerSvnr;
        this.lehrerEmail = lehrerEmail;
        this.lehrerIstAv = lehrerIstAv;
        this.lehrerIstTelVer = lehrerIstTelVer;
        this.lehrerGeschlecht = lehrerGeschlecht;
    }

    public Lehrer(String lehrerKb, Titel titel, String lehrerVorname, String lehrerZuname, String lehrerPasswort, String lehrerSvnr, String lehrerEmail, Double lehrerMaxnegativ, String lehrerTelefonnr, boolean lehrerIstAv, boolean lehrerIstTelVer, String lehrerGeschlecht, Set<LaufendeNote> laufendeNotes, Set<Semesternote> semesternotes, Set<Sprechstunde> sprechstundes, Set<Berechtigung> berechtigungs, Set<Klasse> klasses, Set<Kategorie> kategories, Set<Direktionsdaten> direktionsdatens, Set<Lehrfach> lehrfaches, Set<Pruefung> pruefungs, Set<Mahnung> mahnungs) {
        this.lehrerKb = lehrerKb;
        this.titel = titel;
        this.lehrerVorname = lehrerVorname;
        this.lehrerZuname = lehrerZuname;
        this.lehrerPasswort = lehrerPasswort;
        this.lehrerSvnr = lehrerSvnr;
        this.lehrerEmail = lehrerEmail;
        this.lehrerMaxnegativ = lehrerMaxnegativ;
        this.lehrerTelefonnr = lehrerTelefonnr;
        this.lehrerIstAv = lehrerIstAv;
        this.lehrerIstTelVer = lehrerIstTelVer;
        this.lehrerGeschlecht = lehrerGeschlecht;
        this.laufendeNoten = laufendeNotes;
        this.semesternoten = semesternotes;
        this.sprechstunden = sprechstundes;
        this.berechtigungen = berechtigungs;
        this.klassen = klasses;
        this.kategorien = kategories;
        this.direktionsdaten = direktionsdatens;
        this.lehrfaecher = lehrfaches;
        this.pruefungen = pruefungs;
        this.mahnungen = mahnungs;
    }

    @Id

    @Column(name = "lehrer_kb", unique = true, nullable = false, length = 4)
    public String getLehrerKb() {
        return this.lehrerKb;
    }

    public void setLehrerKb(String lehrerKb) {
        this.lehrerKb = lehrerKb;
    }

    @ManyToOne
    @JoinColumn(name = "lehrer_tit_id")
    public Titel getTitel() {
        return this.titel;
    }

    public void setTitel(Titel titel) {
        this.titel = titel;
    }

    @Column(name = "lehrer_vorname", nullable = false, length = 30)
    public String getLehrerVorname() {
        return this.lehrerVorname;
    }

    public void setLehrerVorname(String lehrerVorname) {
        this.lehrerVorname = lehrerVorname;
    }

    @Column(name = "lehrer_zuname", nullable = false, length = 30)
    public String getLehrerZuname() {
        return this.lehrerZuname;
    }

    public void setLehrerZuname(String lehrerZuname) {
        this.lehrerZuname = lehrerZuname;
    }

    @Column(name = "lehrer_passwort", nullable = false, length = 15)
    public String getLehrerPasswort() {
        return this.lehrerPasswort;
    }

    public void setLehrerPasswort(String lehrerPasswort) {
        this.lehrerPasswort = lehrerPasswort;
    }

    @Column(name = "lehrer_svnr", nullable = false, length = 10)
    public String getLehrerSvnr() {
        return this.lehrerSvnr;
    }

    public void setLehrerSvnr(String lehrerSvnr) {
        this.lehrerSvnr = lehrerSvnr;
    }

    @Column(name = "lehrer_email", nullable = false, length = 50)
    public String getLehrerEmail() {
        return this.lehrerEmail;
    }

    public void setLehrerEmail(String lehrerEmail) {
        this.lehrerEmail = lehrerEmail;
    }

    @Column(name = "lehrer_maxnegativ", precision = 17, scale = 17)
    public Double getLehrerMaxnegativ() {
        return this.lehrerMaxnegativ;
    }

    public void setLehrerMaxnegativ(Double lehrerMaxnegativ) {
        this.lehrerMaxnegativ = lehrerMaxnegativ;
    }

    @Column(name = "lehrer_telefonnr", length = 20)
    public String getLehrerTelefonnr() {
        return this.lehrerTelefonnr;
    }

    public void setLehrerTelefonnr(String lehrerTelefonnr) {
        this.lehrerTelefonnr = lehrerTelefonnr;
    }

    @Column(name = "lehrer_ist_av", nullable = false)
    public boolean isLehrerIstAv() {
        return this.lehrerIstAv;
    }

    public void setLehrerIstAv(boolean lehrerIstAv) {
        this.lehrerIstAv = lehrerIstAv;
    }

    @Column(name = "lehrer_ist_tel_ver", nullable = false)
    public boolean isLehrerIstTelVer() {
        return this.lehrerIstTelVer;
    }

    public void setLehrerIstTelVer(boolean lehrerIstTelVer) {
        this.lehrerIstTelVer = lehrerIstTelVer;
    }

    @Column(name = "lehrer_geschlecht", nullable = false, length = 1)
    public String getLehrerGeschlecht() {
        return this.lehrerGeschlecht;
    }

    public void setLehrerGeschlecht(String lehrerGeschlecht) {
        this.lehrerGeschlecht = lehrerGeschlecht;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<LaufendeNote> getLaufendeNoten() {
        return this.laufendeNoten;
    }

    public void setLaufendeNoten(Set<LaufendeNote> laufendeNoten) {
        this.laufendeNoten = laufendeNoten;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Semesternote> getSemesternoten() {
        return this.semesternoten;
    }

    public void setSemesternoten(Set<Semesternote> semesternoten) {
        this.semesternoten = semesternoten;
    }

    @OneToMany(mappedBy = "lehrer", fetch = FetchType.EAGER)
    public Set<Sprechstunde> getSprechstunden() {
        return this.sprechstunden;
    }

    public void setSprechstunden(Set<Sprechstunde> sprechstunden) {
        this.sprechstunden = sprechstunden;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Berechtigung> getBerechtigungen() {
        return this.berechtigungen;
    }

    public void setBerechtigungen(Set<Berechtigung> berechtigungen) {
        this.berechtigungen = berechtigungen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Klasse> getKlassen() {
        return this.klassen;
    }

    public void setKlassen(Set<Klasse> klassen) {
        this.klassen = klassen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Kategorie> getKategorien() {
        return this.kategorien;
    }

    public void setKategorien(Set<Kategorie> kategorien) {
        this.kategorien = kategorien;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Direktionsdaten> getDirektionsdaten() {
        return this.direktionsdaten;
    }

    public void setDirektionsdaten(Set<Direktionsdaten> direktionsdaten) {
        this.direktionsdaten = direktionsdaten;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Lehrfach> getLehrfaecher() {
        return this.lehrfaecher;
    }

    public void setLehrfaecher(Set<Lehrfach> lehrfaecher) {
        this.lehrfaecher = lehrfaecher;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Pruefung> getPruefungen() {
        return this.pruefungen;
    }

    public void setPruefungen(Set<Pruefung> pruefungen) {
        this.pruefungen = pruefungen;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lehrer")
    public Set<Mahnung> getMahnungen() {
        return this.mahnungen;
    }

    public void setMahnungen(Set<Mahnung> mahnungen) {
        this.mahnungen = mahnungen;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.lehrerKb);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Lehrer other = (Lehrer) obj;
        if (!Objects.equals(this.lehrerKb, other.lehrerKb)) {
            return false;
        }
        return true;
    }

}
