package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", schema = "public"
)
@SequenceGenerator(name="news_seq", sequenceName="news_seq", allocationSize=1)
public class News implements java.io.Serializable {

    private int newsId;
    private String newsTitel;
    private String newsText;
    private Date newsTimestamp;

    public News() {
    }

    public News(String newsTitel, Date newsTimestamp) {
        this.newsTitel = newsTitel;
        this.newsTimestamp = newsTimestamp;
    }
    
    public News(int newsId, String newsTitel, Date newsTimestamp) {
        this.newsId = newsId;
        this.newsTitel = newsTitel;
        this.newsTimestamp = newsTimestamp;
    }

    public News(int newsId, String newsTitel, String newsText, Date newsTimestamp) {
        this.newsId = newsId;
        this.newsTitel = newsTitel;
        this.newsText = newsText;
        this.newsTimestamp = newsTimestamp;
    }

    @Id
    @GeneratedValue(generator = "news_seq")
    @Column(name = "news_id", unique = true, nullable = false)
    public int getNewsId() {
        return this.newsId;
    }

    public void setNewsId(int newsId) {
        this.newsId = newsId;
    }

    @Column(name = "news_titel", nullable = false)
    public String getNewsTitel() {
        return this.newsTitel;
    }

    public void setNewsTitel(String newsTitel) {
        this.newsTitel = newsTitel;
    }

    @Column(name = "news_text")
    public String getNewsText() {
        return this.newsText;
    }

    public void setNewsText(String newsText) {
        this.newsText = newsText;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "news_timestamp", nullable = false, length = 29)
    public Date getNewsTimestamp() {
        return this.newsTimestamp;
    }

    public void setNewsTimestamp(Date newsTimestamp) {
        this.newsTimestamp = newsTimestamp;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.newsId;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final News other = (News) obj;
        if (this.newsId != other.newsId) {
            return false;
        }
        return true;
    }

    
    
}
