package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Ort generated by hbm2java
 */
@Entity
@Table(name = "ort", schema = "public"
)
@SequenceGenerator(name="ort_seq", sequenceName="ort_seq", allocationSize=1)
public class Ort implements java.io.Serializable {

    private int ortId;
    private String ortPlz;
    private String ortName;
    private Set<Schueler> schueler = new HashSet<Schueler>(0);
    private Set<Erziehungsberechtigter> erziehungsberechtigte = new HashSet<Erziehungsberechtigter>(0);

    public Ort() {
    }

    public Ort(int ortId, String ortPlz, String ortName) {
        this.ortId = ortId;
        this.ortPlz = ortPlz;
        this.ortName = ortName;
    }

    public Ort(int ortId, String ortPlz, String ortName, Set<Schueler> schuelers, Set<Erziehungsberechtigter> erziehungsberechtigters) {
        this.ortId = ortId;
        this.ortPlz = ortPlz;
        this.ortName = ortName;
        this.schueler = schuelers;
        this.erziehungsberechtigte = erziehungsberechtigters;
    }

    @Id
    @GeneratedValue(generator = "ort_seq")
    @Column(name = "ort_id", unique = true, nullable = false)
    public int getOrtId() {
        return this.ortId;
    }

    public void setOrtId(int ortId) {
        this.ortId = ortId;
    }

    @Column(name = "ort_plz", nullable = false, length = 6)
    public String getOrtPlz() {
        return this.ortPlz;
    }

    public void setOrtPlz(String ortPlz) {
        this.ortPlz = ortPlz;
    }

    @Column(name = "ort_name", nullable = false, length = 50)
    public String getOrtName() {
        return this.ortName;
    }

    public void setOrtName(String ortName) {
        this.ortName = ortName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ort")
    public Set<Schueler> getSchueler() {
        return this.schueler;
    }

    public void setSchueler(Set<Schueler> schueler) {
        this.schueler = schueler;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ort")
    public Set<Erziehungsberechtigter> getErziehungsberechtigte() {
        return this.erziehungsberechtigte;
    }

    public void setErziehungsberechtigte(Set<Erziehungsberechtigter> erziehungsberechtigte) {
        this.erziehungsberechtigte = erziehungsberechtigte;
    }

}
