package at.htlstp.projekt.p04.model;
// Generated 13.12.2016 11:01:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Titel generated by hbm2java
 */
@Entity
@Table(name = "titel", schema = "public"
)
@SequenceGenerator(name="tit_seq", sequenceName="tit_seq", allocationSize=1)
public class Titel implements java.io.Serializable {

    private int titId;
    private String titBez;
    private Set<Lehrer> lehrer = new HashSet<Lehrer>(0);
    private Set<Erziehungsberechtigter> erziehungsberechtigte = new HashSet<Erziehungsberechtigter>(0);

    public Titel() {
    }

    public Titel(String titBez) {
        this.titBez = titBez;
    }
    
    public Titel(int titId, String titBez) {
        this.titId = titId;
        this.titBez = titBez;
    }

    public Titel(int titId, String titBez, Set<Lehrer> lehrers, Set<Erziehungsberechtigter> erziehungsberechtigters) {
        this.titId = titId;
        this.titBez = titBez;
        this.lehrer = lehrers;
        this.erziehungsberechtigte = erziehungsberechtigters;
    }

    @Id
    @GeneratedValue(generator = "tit_seq")
    @Column(name = "tit_id", unique = true, nullable = false)
    public int getTitId() {
        return this.titId;
    }

    public void setTitId(int titId) {
        this.titId = titId;
    }

    @Column(name = "tit_bez", nullable = false, length = 30)
    public String getTitBez() {
        return this.titBez;
    }

    public void setTitBez(String titBez) {
        this.titBez = titBez;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titel")
    public Set<Lehrer> getLehrer() {
        return this.lehrer;
    }

    public void setLehrer(Set<Lehrer> lehrer) {
        this.lehrer = lehrer;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titel")
    public Set<Erziehungsberechtigter> getErziehungsberechtigte() {
        return this.erziehungsberechtigte;
    }

    public void setErziehungsberechtigte(Set<Erziehungsberechtigter> erziehungsberechtigte) {
        this.erziehungsberechtigte = erziehungsberechtigte;
    }

}
